image: alpine:3.7

services:
  - docker:19.03.5-dind


stages:
  - build
  - compile
  - test
  - quality
  - clouddeploy_aws
  - clouddeploy_gck
  - clouddeploy_azure


variables:
  DOCKER_DRIVER: "overlay2"
  DOCKER_HOST: tcp://docker:2375

Compile:
  stage: compile
  script:
    - echo "compile"

Build:
  stage: build
  script:
    - apk add docker make npm git
    - docker ps
    - docker images
    - IMAGE="beelogger-admin"
    - IMAGE_BEELOGGER_ADMIN=$IMAGE"_"$CI_BUILD_ID":"`docker images | awk  'NR==2 {print $2}' `
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "pushing "
    #- docker push mschlech/$IMAGE $IMAGE_BEELOGGER_ADMIN

test:
  stage: test
  script:
    - echo "testing"

quality_check_beelogger_admin:
  stage: quality
  script:
    - echo "quality check beelogger-admin"

deployAWS:
  stage: clouddeploy_aws
  script:
    - echo "deploy all containers to kubernetes clusters / services aws"

deployGCK:
  stage: clouddeploy_gck
  script:
    - echo "deploy all containers to kubernetes clusters / services gck"

deployAzure:
  stage: clouddeploy_azure
  script:
    - echo "deploy all containers to kubernetes clusters / services azure"
