apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: beelogger-admin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        label-key : label-value
    spec:
      containers:
        - name: beelogger-admin
          image: beelogger/beelogger-admin:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 80
