apiVersion: apps/v1
kind: Deployment
metadata:
  name: beelogger-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beelogger-admin
  template:
    metadata:
      labels:
        app: beelogger-admin
    spec:
      containers:
        - name: app
          image: beelogger/beelogger-admin:v1
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
